-- Generated catalog snapshot. Review owner edits before re-running.
begin;
insert into public.categories (id,name,description,sort_order) values ('zupy','Zupy','',0) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('zestawy','Zestawy','',1) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('nigiri','Nigiri','2 szt',2) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('gunkan','Gunkan','2 szt',3) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('maki-roll','Maki roll','6 szt',4) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('california','California','8 szt',5) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('smok','Smok','8 szt',6) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('futomaki','Futomaki','8 szt',7) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('crunch','Crunch','8 szt',8) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('filadelfia','Filadelfia','8 szt',9) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('smazone-rolki','Smażone rolki','',10) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('pieczone-rolki','Pieczone rolki','8 szt',11) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('smazony-ryz-tiachan','Smażony ryż tiachan','',12) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('salatki','Sałatki','',13) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('przekaski','Przekąski','',14) on conflict (id) do nothing;
insert into public.categories (id,name,description,sort_order) values ('dodatki','Dodatki','',15) on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('miso-klasyczna','zupy','miso-klasyczna','Miso klasyczna','Tofu, shiitake, wakame, sezam, szczypior',2000,null,null,'/images/menu/miso-klasyczna.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('miso-z-lososiem','zupy','miso-z-lososiem','Miso z łososiem','Tofu, shiitake, wakame, sezam, szczypior',2500,null,null,'/images/menu/miso-z-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('maki-set','zestawy','maki-set','Maki Set','36 szt.
6x maki z łososiem, 
6x maki z węgorzem, 
6x maki z krewetką,
6x maki z wędzonym łososiem,
6x maki z ogórkiem,
6x maki z awokado',10900,null,36,'/images/menu/maki-set.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('pieczony-set','zestawy','pieczony-set','Pieczony set','24 szt.
8x Pieczony rol z krewetką,
8x pieczony rol z węgorzem,
8x pieczony rol z łososiem',12000,null,24,'/images/baked-set-1000.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('zestaw-mini-smok','zestawy','zestaw-mini-smok','Zestaw Mini Smok','24 szt.
8x pomarańczowy smok, 
8x złoty smok,
8x zielony smok',12500,null,24,'/images/mini-smok-1000.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('beer-set','zestawy','beer-set','Beer Set','30 szt.
8x futomaki z wędzonym kurczakiem, 
8x kalifornia z wędzonym łososiem,
8x kalifornia z lekko słonym łososiem, 
6x krewetki w tempurze',14500,null,30,'/images/menu/beer-set.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('fila-set','zestawy','fila-set','Fila Set','32 szt.
8x fila łosoś,
8x fila ebi,
8x fila unagi,
8x fila z wędzonym łososiem',15000,null,32,'/images/menu/fila-set.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('set-z-lososiem','zestawy','set-z-lososiem','Set z Łososiem','32 szt.
8x fila łosoś, 
8x fila z krewetką w tempurze, 
8x kalifornia z łososiem,  
6x maki z łososiem, 
2x nigiri z łososiem',15000,null,32,'/images/menu/set-z-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('zestaw-krewetkowy','zestawy','zestaw-krewetkowy','Zestaw Krewetkowy','36 szt.
8x fila ebi,
8x kranch z krewetką, 
8x fila double shrimp,  
6x maki z krewetką, 
6x maki z krewetką w tempurze',17000,null,36,'/images/menu/zestaw-krewetkowy.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('zestaw-mega-smok','zestawy','zestaw-mega-smok','Zestaw Mega Smok','48 szt.
8x czerwony smok, 
8x pomarańczowy smok,  
8x złoty smok,  
8x zielony smok, 
8x tygrysowy smok, 
8x tempura smok,',26000,null,48,'/images/menu/zestaw-mega-smok.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('party-set','zestawy','party-set','Party Set','64 szt.
8x fila z łososiem,
8x kalifornia z wędzonym łososiem, 
8x kalifornia klasyczna,
8x zielony smok, 
8x fila cheddar, 
8x fila ebi,
8x futomaki fudzi, 
8x krancz z krewetką w tempurze',29900,null,64,'/images/party-set-1000.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('nigiri-z-lososiem','nigiri','nigiri-z-lososiem','Nigiri z łososiem','',2200,null,2,'/images/menu/nigiri-z-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('nigiri-z-krewetka','nigiri','nigiri-z-krewetka','Nigiri z krewetką','',2200,null,2,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('nigiri-z-wedzonym-lososiem','nigiri','nigiri-z-wedzonym-lososiem','Nigiri z wędzonym łososiem','',2300,null,2,'/images/menu/nigiri-z-wedzonym-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('nigiri-z-tunczykiem','nigiri','nigiri-z-tunczykiem','Nigiri z tuńczykiem','',2400,null,2,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('nigiri-z-wegorzem','nigiri','nigiri-z-wegorzem','Nigiri z węgorzem','',2400,null,2,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('gunkan-z-hiyashi','gunkan','gunkan-z-hiyashi','Gunkan z hiyashi','',2200,null,2,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('gunkan-z-masago','gunkan','gunkan-z-masago','Gunkan z masago','',2400,null,2,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('maki-z-ogorkiem','maki-roll','maki-z-ogorkiem','Maki z ogórkiem','',1500,null,6,'/images/menu/maki-z-ogorkiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('maki-z-surimi','maki-roll','maki-z-surimi','Maki z surimi','',1600,null,6,'/images/menu/maki-z-surimi.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('maki-z-awokado','maki-roll','maki-z-awokado','Maki z awokado','',1700,null,6,'/images/menu/maki-z-awokado.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('maki-z-krewetka','maki-roll','maki-z-krewetka','Maki z krewetką','',2400,null,6,'/images/menu/maki-z-krewetka.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('maki-z-lososiem','maki-roll','maki-z-lososiem','Maki z łososiem','',2400,null,6,'/images/menu/maki-z-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('maki-z-wedzonym-lososiem','maki-roll','maki-z-wedzonym-lososiem','Maki z wędzonym łososiem','',2500,null,6,'/images/menu/maki-z-wedzonym-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('maki-z-tunczykiem','maki-roll','maki-z-tunczykiem','Maki z tuńczykiem','',2500,null,6,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('maki-z-wegorzem','maki-roll','maki-z-wegorzem','Maki z węgorzem','',2500,null,6,'/images/menu/maki-z-wegorzem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('maki-z-krewetka-w-tempurze','maki-roll','maki-z-krewetka-w-tempurze','Maki z krewetką w tempurze','',2600,null,6,'/images/menu/maki-z-krewetka-w-tempurze.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('kalifornia-klasyczna','california','kalifornia-klasyczna','Kalifornia klasyczna','Surimi, masago, ogórek, awokado, majonez',3600,null,8,'/images/menu/kalifornia-klasyczna.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('kalifornia-z-lososiem','california','kalifornia-z-lososiem','Kalifornia z łososiem','Masago, awokado, ogórek',3700,null,8,'/images/menu/kalifornia-z-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('kalifornia-z-wedzonym-lososiem','california','kalifornia-z-wedzonym-lososiem','Kalifornia z wędzonym łososiem','Sezam, awokado, ogórek',3800,null,8,'/images/menu/kalifornia-z-wedzonym-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('kalifornia-z-lekko-solonym-lososiem','california','kalifornia-z-lekko-solonym-lososiem','Kalifornia z lekko solonym łososiem','Sezam, awokado, ogórek',3800,null,8,'/images/menu/kalifornia-z-lekko-solonym-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('zielony-smok','smok','zielony-smok','Zielony smok','Awokado, węgorz, masago, ogórek, tamago',4500,null,8,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('pomaranczowy-smok','smok','pomaranczowy-smok','Pomarańczowy smok','Łosoś węgorz, masago, ogórek, tamago',4600,null,8,'/images/orange-smok-1000.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('tygrysowy-smok','smok','tygrysowy-smok','Tygrysowy smok','Krewetka ebi, węgorz, masago, ogórek, tamago',4700,null,8,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('czerwony-smok','smok','czerwony-smok','Czerwony smok','Tuńczyk, węgorz, masago, ogórek, tamago',4800,null,8,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('zloty-smok','smok','zloty-smok','Złoty smok','Węgorz, masago, ogórek, tamago',4800,null,8,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('futomaki-z-wedzonym-kurczakiem','futomaki','futomaki-z-wedzonym-kurczakiem','Futomaki z wędzonym kurczakiem','Szczypior, pomidor, ogórek, sałata lodowa, sos sriracza mayo',3500,null,8,'/images/menu/futomaki-z-wedzonym-kurczakiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('futomaki-z-lososiem-i-serem-cheddar','futomaki','futomaki-z-lososiem-i-serem-cheddar','Futomaki z łososiem i serem cheddar','Serek, krewetka gotowana, mix z surimi, sałata lodowa, cheddar, łosoś',3800,null,8,'/images/menu/futomaki-z-lososiem-i-serem-cheddar.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('futomaki-fudzi','futomaki','futomaki-fudzi','Futomaki Fudzi','Serek, awokado, z góry mieszanka z łososia, sosu sojowego, sezamu i oleju sezamowego',3800,null,8,'/images/menu/futomaki-fudzi.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('krancz-z-surimi','crunch','krancz-z-surimi','Krancz z surimi','Masago, chrupki, ogórek, shiitake, majonez',3300,null,8,'/images/menu/krancz-z-surimi.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('krancz-z-krewetka-w-tempurze','crunch','krancz-z-krewetka-w-tempurze','Krancz z krewetką w tempurze','Masago, chrupki, ogórek, majonez',3600,null,8,'/images/menu/krancz-z-krewetka-w-tempurze.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('filadelfia-z-lososiem','filadelfia','filadelfia-z-lososiem','Filadelfia z łososiem','Serek, awokado',3700,null,8,'/images/filadelfia-1000.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('filadelfia-cheddar','filadelfia','filadelfia-cheddar','Filadelfia cheddar','Serek, łosoś lekko słony',3800,null,8,'/images/menu/filadelfia-cheddar.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('filadelfia-z-wedzonym-lososiem','filadelfia','filadelfia-z-wedzonym-lososiem','Filadelfia z wędzonym łososiem','Serek, ogórek',3900,null,8,'/images/menu/filadelfia-z-wedzonym-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('filadelfia-z-krewetka-w-tempurze','filadelfia','filadelfia-z-krewetka-w-tempurze','Filadelfia z krewetką w tempurze','Serek, ogórek, łosoś',4300,null,8,'/images/menu/filadelfia-z-krewetka-w-tempurze.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('filadelfia-unagi','filadelfia','filadelfia-unagi','Filadelfia unagi','Sezam, serek, masago, węgorz, ogórek, awokado',4400,null,8,'/images/menu/filadelfia-unagi.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('filadelfia-z-tunczykiem','filadelfia','filadelfia-z-tunczykiem','Filadelfia z tuńczykiem','Serek, awokado',4400,null,8,'/images/menu/filadelfia-z-tunczykiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('filadelfia-ebi','filadelfia','filadelfia-ebi','Filadelfia ebi','Serek, łosoś, awokado',4400,null,8,'/images/menu/filadelfia-ebi.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('double-shrimp','filadelfia','double-shrimp','Double Shrimp','Krewetka gotowana, krewetka w tempurze, serek, ogórek, sos słodki chili',4800,null,8,'/images/double-shrimp-1000.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('sendwicz-z-lososiem','smazone-rolki','sendwicz-z-lososiem','Sendwicz z łososiem','Serek, łosoś, awokado i sos słodki chili',3500,null,null,'/images/menu/sendwicz-z-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('sendwicz-cheddar','smazone-rolki','sendwicz-cheddar','Sendwicz cheddar','Ser cheddar, sałata lodowa, łosoś lekko słony, sos słodki chili',3500,null,null,'/images/menu/sendwicz-cheddar.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('smazony-z-lososiem-i-krewetka','smazone-rolki','smazony-z-lososiem-i-krewetka','Smażony z łososiem i krewetką','8 szt.
Masago, awokado, ogórek, łosoś, krewetka gotowana, serek',3700,null,8,'/images/menu/smazony-z-lososiem-i-krewetka.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('smazony-tempura-smok','smazone-rolki','smazony-tempura-smok','Smażony tempura smok','8 szt.
Węgorz, tamago, awokado, serek',4000,null,8,'/images/menu/smazony-tempura-smok.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('pieczony-z-krewetka','pieczone-rolki','pieczony-z-krewetka','Pieczony z krewetką','Ogórek, surimi, z góry mieszanka z krewetką',4000,null,8,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('pieczony-z-lososiem','pieczone-rolki','pieczony-z-lososiem','Pieczony z łososiem','Awokado, mix z surimi, z góry mieszanka z łososia',4100,null,8,'/images/menu/pieczony-z-lososiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('pieczony-z-wegorzem','pieczone-rolki','pieczony-z-wegorzem','Pieczony z węgorzem','Serek, z góry mieszanka węgorza',4300,null,8,'/images/menu/pieczony-z-wegorzem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('smazony-ryz-tiachan-z-jajkiem','smazony-ryz-tiachan','smazony-ryz-tiachan-z-jajkiem','Smażony ryż tiachan z jajkiem','Ryż, jajo, szczypior, sezam',2500,null,null,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('smazony-ryz-tiachan-z-kurczakiem','smazony-ryz-tiachan','smazony-ryz-tiachan-z-kurczakiem','Smażony ryż tiachan z kurczakiem','Ryż, jajo, szczypior, sezam',3000,null,null,'/images/menu/smazony-ryz-tiachan-z-kurczakiem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('smazony-ryz-tiachan-z-krewetka','smazony-ryz-tiachan','smazony-ryz-tiachan-z-krewetka','Smażony ryż tiachan z krewetką','Ryż, jajo, szczypior, sezam',3200,null,null,'/images/menu/smazony-ryz-tiachan-z-krewetka.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('salatka-goma-wakame','salatki','salatka-goma-wakame','Sałatka goma wakame','',1500,null,null,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('krewetki-w-tempurze-z-sosem','przekaski','krewetki-w-tempurze-z-sosem','Krewetki w tempurze z sosem','6 szt',4200,null,6,'/images/menu/krewetki-w-tempurze-z-sosem.webp',true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('sos-sezamowy','dodatki','sos-sezamowy','Sos sezamowy','',500,null,null,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('sos-teriyaki','dodatki','sos-teriyaki','Sos teriyaki','',500,null,null,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('sos-sriracha-mayo','dodatki','sos-sriracha-mayo','Sos sriracha mayo','',500,null,null,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('imbir-marynowany','dodatki','imbir-marynowany','Imbir marynowany','',500,null,null,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('sos-sojowy','dodatki','sos-sojowy','Sos sojowy','',500,null,null,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('wasabi','dodatki','wasabi','Wasabi','',500,null,null,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
insert into public.products (id,category_id,slug,name,description,price_grosz,weight_grams,pieces,image,available,source_url,verified_at) values ('sos-sriracha','dodatki','sos-sriracha','Sos sriracha','',500,null,null,null,true,'https://wolt.com/en/pol/szczecin-prawobrzeze/restaurant/sushi-smok','2026-09-14') on conflict (id) do nothing;
commit;
